### PR TITLE
Add missing Unitful dependency

### PR DESCRIPTION
**Pull request by AShedko**
Unitful dependency was missing. I added it.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks!

Hope this is useful. I should say that this package might benefit from some reorganization---it was thrown together in a rush while I was working on an overdue Annual Reviews in Neurosci. If you see other ways it can be improved, don't hesitate to make extensive changes.

**Comment by AShedko** [comment]
Thanks! What about that NIfTI.jl thing?

**Comment by timholy** [comment]
Not sure what you mean.

**Comment by AShedko** [comment]
https://github.com/JuliaIO/NIfTI.jl/pull/12
this thing

**Pull request merged**
